name: Java CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Set up GraalVM Native Image toolchain
          uses: helpermethod/graalvm-native-image-toolchain@0.0.2
          with:
            graalvm-version: 21.2.0
            java-version: 11
        - name: Build
          run: ./mvnw package
