name: Java CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Set up GraalVM Native Image toolchain
          uses: helpermethod/graalvm-native-image-toolchain@0.0.2
          with:
            graalvm-version: 21.2.0
            java-version: 11
        - name: Open Web Client Directory
          run: |
            ls -la    
        - name: Build
          run: |
            mvn package
        - name: Rename the artifact to OS-unique name
          shell: bash
          run: |
            value=`cp build/graal/TuringMachine build/graal/TuringMachine-${{ matrix.os }}`
        - name: Publish artifact
          uses: actions/upload-artifact@master
          with:
            name: TuringMachine-${{ matrix.os }}
            path: build/graal
